# Basic golangci-lint configuration for Model Context SDK
run:
  timeout: 5m
  tests: true
  go: '1.24.2'  # Match go.mod version

# We don't specify output format here, as it should be set by command line
# This allows flexibility between CI (which uses --out-format flag) and local runs

linters-settings:
  errcheck:
    check-type-assertions: true

  shadow:
    strict: false

  goimports:
    local-prefixes: github.com/ajitpratap0

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-same-issues: 5
