name: Go Mod Tidy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'

jobs:
  tidy:
    name: Run go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: true

      - name: Run go mod tidy
        run: |
          go mod tidy
          if [[ $(git status --porcelain) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add go.mod go.sum
            git commit -m "chore: go mod tidy"
            git push
          fi
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') 